### ISSUE TITLE
Remove Temp Files

### ISSUE THREAD

**Issue by CurtisColwell** [CurtisColwell/auto_slurm#8]
The system administrator got annoyed that our script doesn't remove the temporary files upon completion.

**Comment by icolwell** [comment]
The temp directory uses `TEMP_DIR=$(mktemp -d)` though, maybe the sysadmin should instead fix his system so that the temp dir is actually a [temp dir](https://en.wikipedia.org/wiki/Temporary_folder). No problem for us to clean up after we are done, I'm just baffled why anyone is bothered by temporary data existing in a temporary directory.

**Comment by CurtisColwell** [comment]
Yeah, I'm not sure. In the email he said our scripts were using up the memory on the node and wasn't leaving room for other users. Maybe it has something to do with the way the scheduler distributes the nodes.

**Comment by icolwell** [comment]
RAM memory or disk memory?

**Comment by CurtisColwell** [comment]
Probably RAM, but the nodes have pretty comparable amounts of RAM and disk anyways. https://hpcrcf.atlassian.net/wiki/spaces/TCP/pages/6763193/Machine+Specifications
